# Generated by Django 3.2.5 on 2022-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0003_sessiondata_dataset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('image_name', models.CharField(db_index=True, max_length=256)),
                ('milvus_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
