# Generated by Django 3.2.5 on 2022-09-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0004_imageembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageembedding',
            name='image_name',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
